#!/bin/bash

#########################################################################################
#                      D  I  S  C  L  A  I  M  E  R
#########################################################################################
# This script/function is provided AS IS without warranty of any kind.
# Author(s) disclaim all implied warranties including, without limitation,
# any implied warranties of merchantability or of fitness for a particular purpose.
# The entire risk arising out of the use or performance of the sample scripts and
# documentation remains with you. In no event shall author(s) be held liable for
# any damages whatsoever (including, without limitation, damages for loss of business
# profits, business interruption, loss of business information, or other pecuniary loss)
# arising out of the use of or inability to use the script or documentation.
#########################################################################################

declare -a templateSites
maxSize=16700000

# Get the name of the Mongo container
mongocontainer=$(docker ps | grep mongo | awk '{print$11}')

# Get the list of the objects in thee templateSites collection in the msc database
templateSites=($( docker exec -ti $mongocontainer sh -c "mongo msc --eval 'DBQuery.shellBatchSize = 200 ; db.templateSites.find({},{templateId:1})'" | awk '{print$7}' | sed 's/[^a-zA-Z0-9-]//g' ))

for ID in "${templateSites[@]}"
do
   :
   # I'm too lazy to try to avoid to mess up with " and ' so I'm preparing the query in a couple of step
   query="Object.bsonsize(db.templateSites.findOne({'templateId':'$ID'}))"
   query="mongo msc --quiet --eval \"$query\""

   # Get the BSON size
   size=$(docker exec -ti $mongocontainer sh -c "$query")
   size=${size//[^[:digit:].-]/}
   sizek=$(( $size/1024 ))

   # Calculate percentage over $maxSize
   percent=$(( $size*100/$maxSize ))

   # Print results
   printf "%-80s  %-10s " "Size of templateSite $ID is: " "$sizek KB"
   printf %.1f "$percent"
   echo "%"
done
